### ISSUE TITLE
h params  module not found and 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by prilcool** [tugstugi/pytorch-dc-tts#17]
Getting following error on windows 10 jupyter notebook  using englishtts.py any help  on how to get this running ?

Traceback (most recent call last):
  File "englishtts.py", line 107, in <module>
    _, Y_t, A = text2mel(L, Y, monotonic_attention=True)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\prilc\Desktop\speech\models\text2mel.py", line 165, in forward
    K, V = self.text_enc(L)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\prilc\Desktop\speech\models\text2mel.py", line 78, in forward
    out = self.embedding(x)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\prilc\Desktop\speech\models\layers.py", line 98, in forward
    return self.embedding(x)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)

**Comment by PLEmbraceMe** [comment]
I meet it,how can i slove it?
