### ISSUE TITLE
Comet message erros when running train-text2mel.py

### ISSUE THREAD

**Issue by fmobrj** [tugstugi/pytorch-dc-tts#2]
Hello,

When running:

python train-text2mel.py --dataset=ljspeech

I am receiving this error:

Traceback (most recent call last):
  File "train-text2mel.py", line 19, in <module>
    from logger import Logger
  File "/media/hdd3tb/pytorch-dc-tts/logger.py", line 7, in <module>
    from comet_ml import Experiment
  File "/home/jamazzon/anaconda3/envs/tts/lib/python3.7/site-packages/comet_ml/__init__.py", line 72, in <module>
    from .pytorch_logger import patch as pytorch_patch
  File "/home/jamazzon/anaconda3/envs/tts/lib/python3.7/site-packages/comet_ml/pytorch_logger.py", line 72, in <module>
    check_module("torch", PYTORCH_ALREADY_IMPORTED_MSG)
  File "/home/jamazzon/anaconda3/envs/tts/lib/python3.7/site-packages/comet_ml/_logging.py", line 249, in check_module
    raise SyntaxError(error_msg)
SyntaxError: Please import comet before importing any torch modules

**Comment by tugstugi** [comment]
it should be now fixed.
