### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAIntTensor instead

### ISSUE THREAD

**Issue by Joee1995** [tugstugi/pytorch-dc-tts#3]
Hello!

I try to train Mongolian TTS, and when I running

`python train-text2mel.py --dataset=mbspeech`

I receive this error: 

> use_gpu True
epoch   0 with lr=1.25e-06
  0%|                                                                                         | 0/3456 [00:00<?, ?audios/s]
Traceback (most recent call last):
    File "train-text2mel.py", line 159, in <module>
        train_epoch_loss = train(epoch, phase='train')
    File "train-text2mel.py", line 76, in train                                                                                                             
        Y_logit, Y, A = text2mel(L, S)
    File "C:\Users\Joee\AppData\Local\conda\conda\envs\ptPy36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
        result = self.forward(*input, **kwargs)
    File "D:\yang\Projects\TTS\code\pytorch-dc-tts\models\text2mel.py", line 165, in forward
        K, V = self.text_enc(L)
    File "C:\Users\Joee\AppData\Local\conda\conda\envs\ptPy36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
        result = self.forward(*input, **kwargs)
    File "D:\yang\Projects\TTS\code\pytorch-dc-tts\models\text2mel.py", line 78, in forward
        out = self.embedding(x)
    File "C:\Users\Joee\AppData\Local\conda\conda\envs\ptPy36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
        result = self.forward(*input, **kwargs)                                                                                                             
    File "D:\yang\Projects\TTS\code\pytorch-dc-tts\models\layers.py", line 98, in forward
        return self.embedding(x)
    File "C:\Users\Joee\AppData\Local\conda\conda\envs\ptPy36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
        result = self.forward(*input, **kwargs)
    File "C:\Users\Joee\AppData\Local\conda\conda\envs\ptPy36\lib\site-packages\torch\nn\modules\sparse.py", line 108, in forward
        self.norm_type, self.scale_grad_by_freq, self.sparse)
    File "C:\Users\Joee\AppData\Local\conda\conda\envs\ptPy36\lib\site-packages\torch\nn\functional.py", line 1076, in embedding
        return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAIntTensor instead (while checking arguments for embedding)

I think I did something wrong, can u help me? Thx!

**Comment by Joee1995** [comment]
environment: cuda-9.0 + cudnn-7.3.1 + python-3.6.7 + torch-0.4.0

**Comment by tugstugi** [comment]
@Joee1995 It is working under Linux/Anaconda/Cuda10/PyTorch1. Maybe it is a windows problem?

I made a Colab notebook: https://colab.research.google.com/drive/1aG_2uDK-sCWkHIReRqm8WW3y8XsI3Ltm

You can follow the commands in the above notebook to replicate an environment which can successfully train DC-TTS.

**Comment by Joee1995** [comment]
Really a windows problem. 

When running in Linux, it works well at first, but there is another error at epoch 18: 

> epoch  18 with lr=1.22e-03
 50%|██████████▌                  | 1728/3456 [00:27<00:26, 66.45audios/s, l1=0.18589, att=0.00016]Traceback (most recent call last):
    File "train-text2mel.py", line 157, in <module>
        train_epoch_loss = train(epoch, phase='train')
    File "train-text2mel.py", line 140, in train
        {'mels-true': S[0, :, :], 'mels-pred': Y[0, :, :], 'attention': A[0, :, :]})
    File "/home/yy/TTS/pytorch-dc-tts/logger.py", line 29, in log_step
        self.writer.add_image('%s/%s' % (self.model_name, key), image_dict[key], step)
    File "/home/yy/anaconda3/envs/ptPy36/lib/python3.6/site-packages/tensorboardX/writer.py", line 427, in add_image
        image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
    File "/home/yy/anaconda3/envs/ptPy36/lib/python3.6/site-packages/tensorboardX/summary.py", line 211, in image
        tensor = convert_to_HWC(tensor, dataformats)
    File "/home/yy/anaconda3/envs/ptPy36/lib/python3.6/site-packages/tensorboardX/utils.py", line 98, in convert_to_HWC
        assert(len(tensor.shape) == len(input_format)), "size of input tensor and input format are different"
AssertionError: size of input tensor and input format are different

Thx!

**Comment by tugstugi** [comment]
Latest TensorboardX version behaves differently. Should be now fixed with https://github.com/tugstugi/pytorch-dc-tts/commit/653fd14b1fb19cdcf4285adcf49f802b8c9b243d

**Comment by b29b** [comment]
@Joee1995 were you able to get it to run in windows later? would be great if anynone can get it to work in windows
